
spring:
  application:
    name: test
  datasource:
    url: jdbc:mysql://database-1.culp65g6zfyc.us-east-2.rds.amazonaws.com:3306/distributed
    username: admin
    password: xzh111xzh111
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080